version: '2'
services:
  mongodb:
    image: mongo:3.6
    volumes:
        - edp_mongodb:/data/db

  girder:
    image: openchemistry/girder:edp
    build:
      context: ../../
      dockerfile: devops/docker/girder/Dockerfile
    command: -d mongodb://mongodb:27017/girder
    volumes:
      - edp_assetstore:/assetstore
    links:
      - mongodb
    ports:
          - 8080:8080
    depends_on:
      - mongodb

  nginx:
    image: openchemistry/nginx:edp
    build:
      context: ../../
      dockerfile: devops/docker/nginx/Dockerfile
    ports:
      - 80:80
    links:
      - girder
    depends_on:
      - girder

volumes:
    edp_assetstore:
    edp_mongodb:
