version: '2'
services:
  mongodb:
    image: mongo:3.6
    volumes:
        - edp_mongodb:/data/db

  girder:
    image: openchemistry/girder:edp
    build:
      context: ../../
      dockerfile: devops/docker/girder/Dockerfile
    command: -d mongodb://mongodb:27017/girder
    volumes:
      - edp_assetstore:/assetstore
    links:
      - mongodb
    ports:
          - 8080:8080
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - mongodb

  nginx:
    image: openchemistry/nginx:edp
    build:
      context: ../../
      dockerfile: devops/docker/nginx/Dockerfile
    ports:
      - 80:80
    links:
      - girder
    depends_on:
      - girder

  rabbit:
    image: rabbitmq:latest

  girder-worker:
    image: openchemistry/girder_worker:edp
    build:
      context: ../../
      dockerfile: devops/docker/girder_worker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    links:
      - rabbit
      - girder
    environment:
      - GIRDER_WORKER_BROKER=amqp://guest:guest@rabbit/
      - GIRDER_WORKER_BACKEND=amqp://guest:guest@rabbit/
    depends_on:
      - rabbit


volumes:
    edp_assetstore:
    edp_mongodb:
