version: 2
jobs:

  test:
    working_directory: ~/repo
    docker:
      - image: girder/girder:2.x-maintenance-py3
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install plugin
          command: |
            girder-install plugin server/edp
      - run:
          name: Install dev requirements
          command: |
            pip3 install -r server/requirements-dev.txt
      - run:
          name: Run the tests
          command: |
            pytest server/

  release:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: create venv
          command: |
            python3 -m venv ../venv
            . ../venv/bin/activate
      - run:
          name: install release dependencies
          command: |
            . ../venv/bin/activate
            pip install twine setuptools_scm
      - run:
          name: build the project
          command: |
            . ../venv/bin/activate
            python3 cli/setup.py sdist
      - run:
          name: release to PyPI
          command: |
            . ../venv/bin/activate
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
workflows:
  version: 2
  ci:
    jobs:
      - test
          filters:
            tags:
              only: /.*?/
      - release:
          requires:
            - test

          filters:
            tags:
              only: /.*?/
            branches:
              only:
                - master